// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GRABBOX_H
#define GRABBOX_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include <ctime>
#include <ratio>
#include <chrono>

/**
 *
 *
 * @author ExampleAuthor
 */
class GrabBox: public Command {
public:
	GrabBox();
	~GrabBox();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
private:
	std::chrono::high_resolution_clock::time_point tstart;
};

#endif
